"""create Priority table

Revision ID: 8f814a36c1a2
Revises: 
Create Date: 2021-12-09 21:46:58.238966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f814a36c1a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_phone_number'), ['phone_number'], unique=False)

    op.create_table('UserRoles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRoles')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_Users_last_name'))
        batch_op.drop_index(batch_op.f('ix_Users_id'))
        batch_op.drop_index(batch_op.f('ix_Users_first_name'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
