ADMISSION_NAME_LENGTH = 75
ADMISSION_DESCRIPTION_LENGTH = 2000
ADMISSION_STUDENT_ID_LENGTH = 30
ADMISSION_SLUG_LENGTH = 50

ADMISSION_REFERRAL_CODE_LENGTH = 30

ADMISSION_STUDENT_FIRST_NAME_LENGTH = 30
ADMISSION_STUDENT_LAST_NAME_LENGTH = 20
