"""create Priority table

Revision ID: 1734f9df110c
Revises: 
Create Date: 2022-01-20 00:35:19.099737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1734f9df110c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('verified_time', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('citizen_id', sa.String(length=12), nullable=True),
    sa.Column('credit_card_number', sa.String(length=20), nullable=True),
    sa.Column('organization_tax_id', sa.String(length=14), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('organization_representer_person_name', sa.String(length=50), nullable=True),
    sa.Column('envoy_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envoy_type_id'], ['EnvoyType.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alternative_id')
    )
    op.create_index(op.f('ix_User_address'), 'User', ['address'], unique=True)
    op.create_index(op.f('ix_User_citizen_id'), 'User', ['citizen_id'], unique=True)
    op.create_index(op.f('ix_User_credit_card_number'), 'User', ['credit_card_number'], unique=True)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_organization_name'), 'User', ['organization_name'], unique=True)
    op.create_index(op.f('ix_User_organization_representer_person_name'), 'User', ['organization_representer_person_name'], unique=True)
    op.create_index(op.f('ix_User_organization_tax_id'), 'User', ['organization_tax_id'], unique=True)
    op.create_index(op.f('ix_User_phone_number'), 'User', ['phone_number'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('AdmissionPresenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('user_joined_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['Admission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id', 'user_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('StudentPresenter',
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('student_joined_time', sa.DateTime(), nullable=False),
    sa.Column('student_paid_time', sa.DateTime(), nullable=True),
    sa.Column('presenter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['presenter_id'], ['AdmissionPresenter.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'presenter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudentPresenter')
    op.drop_table('AdmissionPresenter')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_phone_number'), table_name='User')
    op.drop_index(op.f('ix_User_organization_tax_id'), table_name='User')
    op.drop_index(op.f('ix_User_organization_representer_person_name'), table_name='User')
    op.drop_index(op.f('ix_User_organization_name'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_index(op.f('ix_User_credit_card_number'), table_name='User')
    op.drop_index(op.f('ix_User_citizen_id'), table_name='User')
    op.drop_index(op.f('ix_User_address'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
