"""create Priority table

Revision ID: 1d15f018fa12
Revises: 88d4f0f768e6
Create Date: 2021-12-30 20:28:08.717145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d15f018fa12'
down_revision = '88d4f0f768e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('code', sa.String(length=50), nullable=False))
    op.drop_index('name', table_name='Roles')
    op.create_index(op.f('ix_Roles_code'), 'Roles', ['code'], unique=True)
    op.create_index(op.f('ix_Roles_name'), 'Roles', ['name'], unique=True)
    op.drop_index('ix_Users_id', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.drop_index(op.f('ix_Roles_name'), table_name='Roles')
    op.drop_index(op.f('ix_Roles_code'), table_name='Roles')
    op.create_index('name', 'Roles', ['name'], unique=False)
    op.drop_column('Roles', 'code')
    # ### end Alembic commands ###
