"""create Priority table

Revision ID: 3380e73615b9
Revises: 
Create Date: 2022-01-02 21:03:39.734993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3380e73615b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdmissionTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', mysql.TEXT(length=2000), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['AdmissionTypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Admissions_end_time'), 'Admissions', ['end_time'], unique=False)
    op.create_index(op.f('ix_Admissions_start_time'), 'Admissions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Admissions_start_time'), table_name='Admissions')
    op.drop_index(op.f('ix_Admissions_end_time'), table_name='Admissions')
    op.drop_table('Admissions')
    op.drop_table('AdmissionTypes')
    # ### end Alembic commands ###
