"""create Priority table

Revision ID: 46300dcbef9f
Revises: 6e73346a8ae3
Create Date: 2022-01-11 21:54:35.387372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46300dcbef9f'
down_revision = '6e73346a8ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Admission_slug', table_name='Admission')
    op.drop_column('Admission', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admission', sa.Column('slug', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('ix_Admission_slug', 'Admission', ['slug'], unique=False)
    # ### end Alembic commands ###
