"""create Priority table

Revision ID: 6e73346a8ae3
Revises: a3fa2254a86c
Create Date: 2022-01-10 22:45:24.814721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e73346a8ae3'
down_revision = 'a3fa2254a86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('useradmission_ibfk_2', 'UserAdmission', type_='foreignkey')
    op.create_foreign_key(None, 'UserAdmission', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserAdmission', type_='foreignkey')
    op.create_foreign_key('useradmission_ibfk_2', 'UserAdmission', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
