"""create Priority table

Revision ID: 7de097d09180
Revises: 981c07046e61
Create Date: 2022-01-04 17:54:07.366485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7de097d09180'
down_revision = '981c07046e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_2', 'User', type_='foreignkey')
    op.drop_column('User', 'manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_2', 'User', 'User', ['manager_id'], ['id'])
    # ### end Alembic commands ###
