"""create Priority table

Revision ID: 88d4f0f768e6
Revises: d0c5fcf8e025
Create Date: 2021-12-30 10:43:47.998374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88d4f0f768e6'
down_revision = 'd0c5fcf8e025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_phone_number', table_name='Users')
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=False))
    op.create_index('ix_Users_phone_number', 'Users', ['phone_number'], unique=False)
    # ### end Alembic commands ###
