"""create Priority table

Revision ID: a10090a32d0f
Revises: 
Create Date: 2022-01-02 20:22:42.110395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10090a32d0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roles_code'), 'Roles', ['code'], unique=True)
    op.create_index(op.f('ix_Roles_name'), 'Roles', ['name'], unique=True)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('activated', sa.BOOLEAN(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.create_index(op.f('ix_Users_first_name'), 'Users', ['first_name'], unique=False)
    op.create_index(op.f('ix_Users_last_name'), 'Users', ['last_name'], unique=False)
    op.create_index(op.f('ix_Users_phone_number'), 'Users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_phone_number'), table_name='Users')
    op.drop_index(op.f('ix_Users_last_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_first_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Roles_name'), table_name='Roles')
    op.drop_index(op.f('ix_Roles_code'), table_name='Roles')
    op.drop_table('Roles')
    # ### end Alembic commands ###
