"""create Priority table

Revision ID: a3fa2254a86c
Revises: 6e017a00bffe
Create Date: 2022-01-10 22:44:16.791043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fa2254a86c'
down_revision = '6e017a00bffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('useradmission_ibfk_1', 'UserAdmission', type_='foreignkey')
    op.create_foreign_key(None, 'UserAdmission', 'Admission', ['admission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserAdmission', type_='foreignkey')
    op.create_foreign_key('useradmission_ibfk_1', 'UserAdmission', 'Admission', ['admission_id'], ['id'])
    # ### end Alembic commands ###
