"""create Priority table

Revision ID: b30e8b01a58f
Revises: 
Create Date: 2022-02-15 22:37:34.210778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30e8b01a58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('studentpresenter_ibfk_1', 'StudentPresenter', type_='foreignkey')
    op.create_foreign_key(None, 'StudentPresenter', 'AdmissionPresenter', ['presenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'StudentPresenter', type_='foreignkey')
    op.create_foreign_key('studentpresenter_ibfk_1', 'StudentPresenter', 'AdmissionPresenter', ['presenter_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###
