"""create Priority table

Revision ID: ba8fbf2c4cdc
Revises: 
Create Date: 2022-01-04 17:38:47.881484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba8fbf2c4cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdmissionType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('EnvoyType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EnvoyType_name'), 'EnvoyType', ['name'], unique=True)
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_code'), 'Role', ['code'], unique=True)
    op.create_index(op.f('ix_Role_name'), 'Role', ['name'], unique=True)
    op.create_table('Admission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', mysql.TEXT(length=2000), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['AdmissionType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Admission_end_time'), 'Admission', ['end_time'], unique=False)
    op.create_index(op.f('ix_Admission_start_time'), 'Admission', ['start_time'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('envoy_type_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envoy_type_id'], ['EnvoyType.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_card_number'), 'User', ['card_number'], unique=True)
    op.create_index(op.f('ix_User_citizen_id'), 'User', ['citizen_id'], unique=True)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_phone_number'), 'User', ['phone_number'], unique=False)
    op.create_index(op.f('ix_User_tax_id'), 'User', ['tax_id'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('UserAdmission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['Admission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'admission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAdmission')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_tax_id'), table_name='User')
    op.drop_index(op.f('ix_User_phone_number'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_index(op.f('ix_User_citizen_id'), table_name='User')
    op.drop_index(op.f('ix_User_card_number'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Admission_start_time'), table_name='Admission')
    op.drop_index(op.f('ix_Admission_end_time'), table_name='Admission')
    op.drop_table('Admission')
    op.drop_index(op.f('ix_Role_name'), table_name='Role')
    op.drop_index(op.f('ix_Role_code'), table_name='Role')
    op.drop_table('Role')
    op.drop_index(op.f('ix_EnvoyType_name'), table_name='EnvoyType')
    op.drop_table('EnvoyType')
    op.drop_table('AdmissionType')
    # ### end Alembic commands ###
