"""create Priority table

Revision ID: d0c5fcf8e025
Revises: 2176293f258f
Create Date: 2021-12-30 10:43:15.060661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0c5fcf8e025'
down_revision = '2176293f258f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('full_name', sa.String(length=50), nullable=True))
    op.drop_index('ix_Users_first_name', table_name='Users')
    op.drop_index('ix_Users_last_name', table_name='Users')
    op.create_index(op.f('ix_Users_full_name'), 'Users', ['full_name'], unique=False)
    op.drop_column('Users', 'last_name')
    op.drop_column('Users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('Users', sa.Column('last_name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_index(op.f('ix_Users_full_name'), table_name='Users')
    op.create_index('ix_Users_last_name', 'Users', ['last_name'], unique=False)
    op.create_index('ix_Users_first_name', 'Users', ['first_name'], unique=False)
    op.drop_column('Users', 'full_name')
    # ### end Alembic commands ###
