"""create Priority table

Revision ID: da236f9f8734
Revises: 
Create Date: 2022-01-10 22:40:43.676215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da236f9f8734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Admission_slug'), 'Admission', ['slug'], unique=True)
    op.drop_index('ix_UserAdmission_slug', table_name='UserAdmission')
    op.drop_column('UserAdmission', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAdmission', sa.Column('slug', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('ix_UserAdmission_slug', 'UserAdmission', ['slug'], unique=False)
    op.drop_index(op.f('ix_Admission_slug'), table_name='Admission')
    # ### end Alembic commands ###
