"""create Priority table

Revision ID: ed202aab793f
Revises: 26afc1d5beac
Create Date: 2022-01-04 19:22:23.096820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed202aab793f'
down_revision = '26afc1d5beac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_User_phone_number', table_name='User')
    op.create_index(op.f('ix_User_phone_number'), 'User', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_phone_number'), table_name='User')
    op.create_index('ix_User_phone_number', 'User', ['phone_number'], unique=False)
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
