ENVOY_CITIZEN_ID_LENGTH = 20
ENVOY_CARD_NUMBER_LENGTH = 20
ENVOY_TAX_ID_LENGTH = 20

ENVOY_ORGANIZATION_NAME_LENGTH = 255
ENVOY_ORGANIZATION_REPRESENTER_NAME_LENGTH = 50
ENVOY_ADDRESS_LENGTH = 255

ENVOY_TYPE_NAME_LENGTH = 50
