USER_FIRST_NAME_LENGTH = 30
USER_LAST_NAME_LENGTH = 20
USER_USERNAME_LENGTH = 50

USER_PASSWORD_LENGTH = 255
USER_AVATAR_URL_LENGTH = 255

USER_EMAIL_LENGTH = 50
USER_PHONE_LENGTH = 11

USER_ROLE_LENGTH = 50
